services:
  - docker

before_install:
  - gem install bundler

before_script:
  - docker-compose build
  - cp .env.sample .env

script:
  - docker-compose run app /bin/sh -c "bundle config unset without && bundle install && rake ci"