---
version: '3'
services:
  app:
    image: xtrasimplicity/service-health-registry
    build: .
    environment:
      ADMIN_AUTH_TOKEN:
      DATABASE_NAME:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
    ports:
      - 4567:4567